name: "xccovPretty"
description: "Output Xcode code coverage in a slightly prettier way"
inputs:
  resultBundle:
    description: "The path to your test run’s .xcresult bundle. This must have been produced by xcodebuild."
    required: true
  includedTargets:
    description: "Targets to include in the output. If unspecified, all targets are included."
    required: false
    default: ","
runs:
  using: "composite"
  steps:
    - name: Pretty Print Code Coverage
      shell: bash
      run: ${{ github.action_path }}/xccovPretty.sh
      env:
        RESULT_BUNDLE: ${{ inputs.resultBundle }}
        INCLUDED_TARGETS: ${{ inputs.includedTargets }}
